easy_admin:
    entities:
        Acme:
            class: App\Entity\Acme
        AcmeParent:
            class: App\Entity\AcmeParent
            edit:
                fields:
                    - { property: 'fieldPA' }
                    - { property: 'fieldPB', type_options: { by_reference: false }}