vich_uploader:
    db_driver: orm

    mappings:
        ocr_image:
            uri_prefix: /images/ocr
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer